# Generated by Django 4.0.4 on 2022-04-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('dni', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='DNI')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Nombres')),
                ('lastname', models.CharField(blank=True, max_length=50, verbose_name='Apellidos')),
                ('age', models.IntegerField(blank=True, verbose_name='Edad')),
                ('birthday', models.DateField(blank=True, verbose_name='Fechas de nacimiento')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Direccion')),
                ('workplace', models.CharField(blank=True, max_length=100, verbose_name='Lugar de trabajo')),
                ('phone', models.IntegerField(blank=True, verbose_name='Celular')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
    ]
