# Generated by Django 4.0.4 on 2022-04-25 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Datos del cliente', 'verbose_name_plural': 'Datos de los clientes'},
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo de la consulta')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('temp', models.CharField(blank=True, max_length=20, verbose_name='Temperatura')),
                ('sat', models.CharField(blank=True, max_length=20, verbose_name='Saturacion')),
                ('sick', models.TextField(blank=True, verbose_name='Enfermedades presentes')),
                ('med', models.TextField(blank=True, verbose_name='Medicacion actual')),
                ('treat', models.FileField(upload_to='treatments', verbose_name='Tratamientos')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Cliente')),
            ],
        ),
    ]
