# Generated by Django 4.0.4 on 2022-04-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_options_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Fechas de nacimiento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='client',
            name='workplace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de trabajo'),
        ),
    ]
