# Generated by Django 4.0.4 on 2022-04-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_address_alter_client_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': 'Tratamiento', 'verbose_name_plural': 'Tratamientos'},
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treat',
            field=models.FileField(upload_to='treatments/2022/4/25/', verbose_name='Tratamientos'),
        ),
    ]
